name: eWineFanatic
favicon: null
layout_spectrum: 0.8368072856683284
typography_spectrum: 0.7620877630542964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6220698689576238
  lightness: 0.8622816305141896
  saturation: 0.9744121341500431
  rhythmicContrast: 0.8677378662396222
purpose: []
